### ISSUE TITLE
Document every class

### ISSUE THREAD

**Issue by ggggg** [BPEssentials/Core#49]
We should document most classes eg: core class
/**
*
* Welcome to BPE
*
* BPE is a custom plugin made by User R00T 
*BPE does...
*/

or the atm class
/**
*
* This class allows the user to open the atm menu
*/

**Comment by UserR00T** [comment]
By adding documentation this size you'll increase the overal project size without adding any special benefits. Take a look around at other big projects, not a lot of projects have a header part in all their files. It's just not worth the time.
