### ISSUE TITLE
Essentials not working with 1.04h update

### ISSUE THREAD

**Issue by Spirit1408** [BPEssentials/Core#53]
After launching and loading a plugin BP-CoreLib.dll - got a message "TypeLoadException: Could not resolve type with token 01000014..."
Is there any suggestions or issues, how i could use those plugins?

**Comment by PLASMAchicken** [comment]
Known Issue BPE's Development stopped a while ago, but it might come back for v1.05.

**Comment by Spirit1408** [comment]
Got it, thanks for replying!
Will wait for new updates
