### ISSUE TITLE
Suggestion: RemoveKit In-game command

### ISSUE THREAD

**Issue by MystLeissa** [BPEssentials/Core#76]
Basically a cojmmand to automatically allow removal of a kit for a server admin or appropriately permissioned person. This would allow easier reconfiguration of pre-permed kits if somehow you managed to mess up one while creating it.

Example:

There's a Police Kit in my Server I've created, /removekit Police deletes the kit allowing for a new assignment of gear so I can remove the misplaced Teal Skirt inside.

**Comment by PLASMAchicken** [comment]
I think its possible to delete the file and do /ess reload, but yeah, we will add the commands
